export {default as MainBody} from './MainBody'
export {default as Sidebar} from './Sidebar'
export {default as Card} from './Card'
export {default as Music} from './Music'
export {default as Albums} from './Albums'